import type { ChapterManifest } from './types';
import { bootsStrings as s } from './boots.strings';

// The Boots chapter: the SAME shared house cross-section, focused on the
// foundation. Shared context layers (wall/window/roof) reuse Hat geometry; the
// three Boots teaching layers are additive around the footing, with bbox values
// measured from the real SVGs and explodeOffset in viewBox units.
// Reader-facing words come from boots.strings (the i18n seam).
export const bootsManifest: ChapterManifest = {
  slug: 'boots',
  meta: { title: 'The Boots', kicker: 'What a foundation knows about water' },
  subtitle: s.chapterSubtitle,
  intro: s.intro,
  whyItMatters: s.whyItMatters,
  sourcedAside: s.sourcedAside,
  sources: s.sources,
  layers: [
    // --- the foundation (the focus) -----------------------------------------
    {
      id: 'footing',
      src: 'book/hat/footing.svg',
      label: s.layerLabels['footing'],
      alt: 'The footing and piers',
      tabColor: '#9aa7b3',
      tabWord: 'FOOTING',
      z: 20,
      explodeOffset: { x: 0, y: 80 },
      bbox: { x: 40, y: 300, w: 280, h: 44 },
    },
    // --- the Boots teaching layers (measured bboxes) ------------------------
    {
      id: 'grade-and-drain',
      src: 'book/boots/grade-and-drain.svg',
      label: s.layerLabels['grade-and-drain'],
      alt: 'Sloped grade and drainage away from the base',
      tabColor: '#5b86a8',
      tabWord: 'GRADE',
      z: 18,
      explodeOffset: { x: -90, y: 50 },
      bbox: { x: 40, y: 300, w: 280, h: 44 },
    },
    {
      id: 'frost-depth',
      src: 'book/boots/frost-depth.svg',
      label: s.layerLabels['frost-depth'],
      alt: 'The frost line the footing must sit below',
      tabColor: '#7fa8c9',
      tabWord: 'FROST',
      z: 19,
      explodeOffset: { x: 95, y: 30 },
      bbox: { x: 40, y: 300, w: 280, h: 39 },
    },
    {
      id: 'capillary-break',
      src: 'book/boots/capillary-break.svg',
      label: s.layerLabels['capillary-break'],
      alt: 'A capillary break stopping water wicking up',
      tabColor: '#38bdf8',
      tabWord: 'BREAK',
      z: 22,
      explodeOffset: { x: 95, y: -20 },
      bbox: { x: 148, y: 294, w: 96, h: 38 },
    },
    // --- shared context (reuse Hat geometry) --------------------------------
    {
      id: 'wall',
      src: 'book/hat/wall.svg',
      label: s.layerLabels['wall'],
      alt: 'The wall above the foundation',
      tabColor: '#c9a86a',
      tabWord: 'WALL',
      z: 30,
      explodeOffset: { x: -90, y: -40 },
      bbox: { x: 148, y: 116, w: 96, h: 188 },
    },
    {
      id: 'window',
      src: 'book/hat/window.svg',
      label: s.layerLabels['window'],
      alt: 'The window opening',
      tabColor: '#7fa8c9',
      tabWord: 'WINDOW',
      z: 31,
      explodeOffset: { x: 90, y: -60 },
      bbox: { x: 182, y: 150, w: 54, h: 103 },
    },
    {
      id: 'roof-overhang',
      src: 'book/hat/roof-overhang.svg',
      label: s.layerLabels['roof-overhang'],
      alt: 'The roof above',
      tabColor: '#c8714a',
      tabWord: 'ROOF',
      z: 40,
      explodeOffset: { x: 0, y: -85 },
      bbox: { x: 110, y: 62, w: 188, h: 88 },
    },
  ],
  steps: [
    {
      id: 'boots-overview',
      heading: s.presetLabels['boots-overview'],
      prose: s.presetDescriptions['boots-overview'],
      takeaway: s.presetTakeaways['boots-overview'],
      dockedLayerIds: ['footing', 'wall', 'window', 'roof-overhang'],
      spotlightLayerId: 'footing',
    },
    {
      id: 'boots-frost',
      heading: s.presetLabels['boots-frost'],
      prose: s.presetDescriptions['boots-frost'],
      takeaway: s.presetTakeaways['boots-frost'],
      dockedLayerIds: [
        'footing',
        'frost-depth',
        'wall',
        'window',
        'roof-overhang',
      ],
      spotlightLayerId: 'frost-depth',
    },
    {
      id: 'boots-water-path',
      heading: s.presetLabels['boots-water-path'],
      prose: s.presetDescriptions['boots-water-path'],
      takeaway: s.presetTakeaways['boots-water-path'],
      dockedLayerIds: [
        'footing',
        'grade-and-drain',
        'wall',
        'window',
        'roof-overhang',
      ],
      spotlightLayerId: 'grade-and-drain',
    },
    {
      id: 'boots-capillary-break',
      heading: s.presetLabels['boots-capillary-break'],
      prose: s.presetDescriptions['boots-capillary-break'],
      takeaway: s.presetTakeaways['boots-capillary-break'],
      dockedLayerIds: [
        'footing',
        'grade-and-drain',
        'capillary-break',
        'wall',
        'window',
        'roof-overhang',
      ],
      spotlightLayerId: 'capillary-break',
    },
  ],
};
