import type { ChapterManifest } from './types';
import { coatStrings as s } from './coat.strings';

// The Coat chapter: the SAME shared house cross-section, focused on the wall
// envelope. Shared context layers (footing/wall/window/roof) reuse Hat's measured
// geometry so the building registers identically across chapters. The four Coat
// teaching layers are additive inside the wall; their bbox values were measured
// from the real SVGs (getBBox in-browser), explodeOffset is in viewBox units.
// Reader-facing words come from coat.strings (the i18n seam).
export const coatManifest: ChapterManifest = {
  slug: 'coat',
  meta: { title: 'The Coat', kicker: 'What a wall knows about the cold' },
  displayTitle: s.chapterTitle,
  subtitle: s.chapterSubtitle,
  intro: s.intro,
  whyItMatters: s.whyItMatters,
  sourcedAside: s.sourcedAside,
  sources: s.sources,
  layers: [
    // --- shared context (reuse Hat geometry) --------------------------------
    {
      id: 'footing',
      src: 'book/hat/footing.svg',
      label: s.layerLabels['footing'],
      alt: 'The footing the wall stands on',
      tabColor: '#9aa7b3',
      tabWord: 'FOOTING',
      z: 10,
      explodeOffset: { x: 0, y: 70 },
      bbox: { x: 40, y: 300, w: 280, h: 44 },
    },
    {
      id: 'roof-overhang',
      src: 'book/hat/roof-overhang.svg',
      label: s.layerLabels['roof-overhang'],
      alt: 'The roof above the wall',
      tabColor: '#c8714a',
      tabWord: 'ROOF',
      z: 60,
      explodeOffset: { x: 0, y: -80 },
      bbox: { x: 110, y: 62, w: 188, h: 88 },
    },
    {
      id: 'wall',
      src: 'book/hat/wall.svg',
      label: s.layerLabels['wall'],
      alt: 'The framed wall',
      tabColor: '#b88b50',
      tabWord: 'WALL',
      z: 20,
      explodeOffset: { x: -95, y: 0 },
      bbox: { x: 148, y: 116, w: 96, h: 188 },
    },
    {
      id: 'window',
      src: 'book/hat/window.svg',
      label: s.layerLabels['window'],
      alt: 'The window opening',
      tabColor: '#7fa8c9',
      tabWord: 'WINDOW',
      z: 30,
      explodeOffset: { x: -95, y: -70 },
      bbox: { x: 182, y: 150, w: 54, h: 103 },
    },
    // --- the Coat teaching layers (measured bboxes) -------------------------
    {
      id: 'cavity-insulation',
      src: 'book/coat/cavity-insulation.svg',
      label: s.layerLabels['cavity-insulation'],
      alt: 'Insulation filling the cavities between the studs',
      tabColor: '#c9a86a',
      tabWord: 'CAVITY',
      z: 32,
      explodeOffset: { x: 70, y: -30 },
      bbox: { x: 150, y: 120, w: 92, h: 180 },
    },
    {
      id: 'continuous-insulation',
      src: 'book/coat/continuous-insulation.svg',
      label: s.layerLabels['continuous-insulation'],
      alt: 'A continuous outer wrap of insulation',
      tabColor: '#5b86a8',
      tabWord: 'WRAP',
      z: 33,
      explodeOffset: { x: 95, y: 30 },
      bbox: { x: 141, y: 112, w: 103, h: 190 },
    },
    {
      id: 'air-vapor-membrane',
      src: 'book/coat/air-vapor-membrane.svg',
      label: s.layerLabels['air-vapor-membrane'],
      alt: 'The air-and-vapor control membrane',
      tabColor: '#38bdf8',
      tabWord: 'AIR SEAL',
      z: 34,
      explodeOffset: { x: 110, y: -10 },
      bbox: { x: 244, y: 122, w: 25, h: 176 },
    },
    {
      id: 'thermal-mass-interior',
      src: 'book/coat/thermal-mass-interior.svg',
      label: s.layerLabels['thermal-mass-interior'],
      alt: 'Interior thermal mass storing heat',
      tabColor: '#b07a3c',
      tabWord: 'MASS',
      z: 35,
      explodeOffset: { x: -110, y: 40 },
      bbox: { x: 150, y: 120, w: 30, h: 180 },
    },
  ],
  steps: [
    {
      id: 'coat-everything',
      heading: s.presetLabels['coat-everything'],
      prose: s.presetDescriptions['coat-everything'],
      takeaway: s.presetTakeaways['coat-everything'],
      dockedLayerIds: [
        'footing',
        'roof-overhang',
        'wall',
        'window',
        'cavity-insulation',
        'continuous-insulation',
        'air-vapor-membrane',
        'thermal-mass-interior',
      ],
      spotlightLayerId: 'continuous-insulation',
    },
    {
      id: 'coat-bare-wall',
      heading: s.presetLabels['coat-bare-wall'],
      prose: s.presetDescriptions['coat-bare-wall'],
      takeaway: s.presetTakeaways['coat-bare-wall'],
      dockedLayerIds: ['footing', 'roof-overhang', 'wall', 'window'],
      spotlightLayerId: 'wall',
    },
    {
      id: 'coat-cavity-plus-wrap',
      heading: s.presetLabels['coat-cavity-plus-wrap'],
      prose: s.presetDescriptions['coat-cavity-plus-wrap'],
      takeaway: s.presetTakeaways['coat-cavity-plus-wrap'],
      dockedLayerIds: [
        'footing',
        'roof-overhang',
        'wall',
        'window',
        'cavity-insulation',
        'continuous-insulation',
      ],
      spotlightLayerId: 'continuous-insulation',
    },
    {
      id: 'coat-air-and-mass',
      heading: s.presetLabels['coat-air-and-mass'],
      prose: s.presetDescriptions['coat-air-and-mass'],
      takeaway: s.presetTakeaways['coat-air-and-mass'],
      dockedLayerIds: [
        'footing',
        'roof-overhang',
        'wall',
        'window',
        'cavity-insulation',
        'continuous-insulation',
        'air-vapor-membrane',
        'thermal-mass-interior',
      ],
      spotlightLayerId: 'air-vapor-membrane',
    },
  ],
};
