import type { ChapterManifest } from './types';
import { hatStrings as s } from './hat.strings';

// Geometry note: explodeOffset + bbox are in VIEWBOX UNITS (0..360), the shared
// coordinate space all 7 layers are drawn in. bbox values are the real measured
// ink bounds of each layer (see memory: hat-svg-real-bboxes). Offsets pull each
// part away from the assembled centre so the building genuinely separates.
// Reader-facing words come from hat.strings (the i18n seam); geometry stays here.
export const hatManifest: ChapterManifest = {
  slug: 'hat',
  meta: { title: 'The Hat', kicker: 'Why a roof needs a brim' },
  displayTitle: s.chapterTitle,
  subtitle: s.chapterSubtitle,
  intro: s.intro,
  whyItMatters: s.whyItMatters,
  sourcedAside: s.sourcedAside,
  sources: s.sources,
  layers: [
    {
      id: 'footing',
      src: 'book/hat/footing.svg',
      label: 'Footing',
      alt: 'The footing and piers the house stands on',
      tabColor: '#9aa7b3',
      tabWord: 'FOOTING',
      z: 10,
      explodeOffset: { x: 0, y: 70 },
      bbox: { x: 40, y: 300, w: 280, h: 44 },
    },
    {
      id: 'wall',
      src: 'book/hat/wall.svg',
      label: 'Walls',
      alt: 'The insulated wall',
      tabColor: '#c9a86a',
      tabWord: 'WALL',
      z: 20,
      explodeOffset: { x: -70, y: 0 },
      bbox: { x: 148, y: 116, w: 96, h: 188 },
    },
    {
      id: 'window',
      src: 'book/hat/window.svg',
      label: 'Window',
      alt: 'The window opening',
      tabColor: '#7fa8c9',
      tabWord: 'WINDOW',
      z: 30,
      explodeOffset: { x: 95, y: 30 },
      bbox: { x: 182, y: 150, w: 54, h: 103 },
    },
    {
      id: 'roof-overhang',
      src: 'book/hat/roof-overhang.svg',
      label: 'Roof overhang',
      alt: 'The roof and its overhang — the hat',
      tabColor: '#c8714a',
      tabWord: 'ROOF',
      z: 60,
      explodeOffset: { x: 0, y: -75 },
      bbox: { x: 110, y: 62, w: 188, h: 88 },
    },
    {
      id: 'sun-high',
      src: 'book/hat/sun-high.svg',
      label: 'Summer sun',
      alt: 'The high summer sun',
      tabColor: '#e8a02e',
      tabWord: 'SUMMER',
      z: 50,
      explodeOffset: { x: 70, y: -55 },
      bbox: { x: 250, y: 20, w: 90, h: 90 },
    },
    {
      id: 'sun-low',
      src: 'book/hat/sun-low.svg',
      label: 'Winter sun',
      alt: 'The low winter sun',
      tabColor: '#e6b455',
      tabWord: 'WINTER',
      z: 50,
      explodeOffset: { x: 95, y: 35 },
      bbox: { x: 280, y: 170, w: 70, h: 70 },
    },
    {
      id: 'rain',
      src: 'book/hat/rain.svg',
      label: 'Rain',
      alt: 'Rain shedding clear of the wall',
      tabColor: '#5b86a8',
      tabWord: 'RAIN',
      z: 55,
      explodeOffset: { x: 40, y: -45 },
      bbox: { x: 116, y: 34, w: 208, h: 60 },
    },
  ],
  // Each step is one teaching view; heading/prose/takeaway come from the strings
  // (the real authored narrative), dockedLayerIds say which parts assemble.
  steps: [
    {
      id: 'everything',
      heading: s.presetLabels['everything'],
      prose: s.presetDescriptions['everything'],
      takeaway: s.presetTakeaways['everything'],
      dockedLayerIds: [
        'footing',
        'wall',
        'window',
        'roof-overhang',
        'sun-high',
        'sun-low',
        'rain',
      ],
      spotlightLayerId: 'roof-overhang',
    },
    {
      id: 'bare-wall',
      heading: s.presetLabels['bare-wall'],
      prose: s.presetDescriptions['bare-wall'],
      takeaway: s.presetTakeaways['bare-wall'],
      dockedLayerIds: ['footing', 'wall', 'window'],
      spotlightLayerId: 'sun-high',
    },
    {
      id: 'roof-line',
      heading: s.presetLabels['roof-line'],
      prose: s.presetDescriptions['roof-line'],
      takeaway: s.presetTakeaways['roof-line'],
      dockedLayerIds: [
        'footing',
        'wall',
        'window',
        'roof-overhang',
        'sun-high',
        'sun-low',
      ],
      spotlightLayerId: 'roof-overhang',
    },
    {
      id: 'how-it-sheds-water',
      heading: s.presetLabels['how-it-sheds-water'],
      prose: s.presetDescriptions['how-it-sheds-water'],
      takeaway: s.presetTakeaways['how-it-sheds-water'],
      dockedLayerIds: ['footing', 'wall', 'window', 'roof-overhang', 'rain'],
      spotlightLayerId: 'rain',
    },
  ],
};
